name: Build macOS App

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build KoreNani
    # Use the current macOS runner which includes the latest Xcode 16.x
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest  # automatically picks the newest installed version

      - name: Show Xcode version & compatibility
        run: |
          xcodebuild -version
          echo "Project object version: $(grep 'objectVersion' korenani.xcodeproj/project.pbxproj)"

      - name: Clean build folder
        run: |
          xcodebuild clean \
            -project korenani.xcodeproj \
            -scheme korenani

      - name: Build project
        run: |
          xcodebuild build \
            -project korenani.xcodeproj \
            -scheme korenani \
            -configuration Release \
            -destination 'platform=macOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Archive project
        run: |
          xcodebuild archive \
            -project korenani.xcodeproj \
            -scheme korenani \
            -configuration Release \
            -destination 'platform=macOS' \
            -archivePath build/KoreNani.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KoreNani-build
          path: build/KoreNani.xcarchive
          retention-days: 30
